import eventsApi from "../features/events/api";
import { tools as eventsTools } from "../features/events/tools";
import type { McpToolDescriptor, ToolDef } from "contracts/mcp";
import type { AnyOperationDef, PartyIntentDescriptor, RegistryOwnershipManifest } from "contracts/operation";
import type { OpenApiDocument, RestRegistrationDescriptor } from "contracts/routes";
import type { Hono } from "hono";
import type { PartyHandler } from "./party/types";

// Generated by scripts/gen.ts. Do not edit by hand.
export const operations: readonly AnyOperationDef[] = [];

export const operationById = Object.fromEntries(
  operations.map((operation) => [operation.id, operation]),
) as Readonly<Record<string, AnyOperationDef>>;

export const restRegistrations: readonly RestRegistrationDescriptor[] = [];

export const mcpTools: readonly McpToolDescriptor[] = [];

export const partyIntents: readonly PartyIntentDescriptor[] = [];

export const openApi = {
  "info": {
    "title": "session-party API",
    "version": "0.1.0"
  },
  "openapi": "3.1.0",
  "paths": {}
} as const satisfies OpenApiDocument;

export const ownershipManifest = {
  "mcp": [],
  "operations": [],
  "party": [],
  "rest": []
} as const satisfies RegistryOwnershipManifest;

// Compatibility exports include only slices that have not cut over to OperationDefs.
export const apiRouters: readonly Hono<{ Bindings: Env }>[] = [eventsApi];
export const tools: readonly ToolDef[] = [...eventsTools];
export const partyHandlers: Readonly<Record<string, PartyHandler>> = {};
