import { operations as eventsOperations } from "../features/events/operations";
import type { McpToolDescriptor, ToolDef } from "contracts/mcp";
import type { AnyOperationDef, PartyIntentDescriptor, RegistryOwnershipManifest } from "contracts/operation";
import type { OpenApiDocument, RestRegistrationDescriptor } from "contracts/routes";
import type { Hono } from "hono";
import type { PartyHandler } from "./party/types";

// Generated by scripts/gen.ts. Do not edit by hand.
export const operations: readonly AnyOperationDef[] = [eventsOperations[0], eventsOperations[2], eventsOperations[1], eventsOperations[3]];

export const operationById = Object.fromEntries(
  operations.map((operation) => [operation.id, operation]),
) as Readonly<Record<string, AnyOperationDef>>;

export const restRegistrations: readonly RestRegistrationDescriptor[] = [
  {
    "input": {
      "body": "all"
    },
    "method": "post",
    "operationId": "events.create",
    "path": "/events",
    "successStatus": 200
  },
  {
    "input": {
      "path": [
        "idOrSlug"
      ]
    },
    "method": "get",
    "operationId": "events.get",
    "path": "/events/:idOrSlug",
    "successStatus": 200
  },
  {
    "input": {},
    "method": "get",
    "operationId": "events.list",
    "path": "/events",
    "successStatus": 200
  },
  {
    "input": {
      "body": [
        "name",
        "slug",
        "description",
        "location",
        "timezone",
        "startsAt",
        "endsAt",
        "accentColor"
      ],
      "path": [
        "idOrSlug"
      ]
    },
    "method": "patch",
    "operationId": "events.update",
    "path": "/events/:idOrSlug",
    "successStatus": 200
  }
];

export const mcpTools: readonly McpToolDescriptor[] = [
  {
    "description": "Get an event by its id or slug.",
    "inputSchema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "idOrSlug": {
          "description": "a string at least 1 character(s) long",
          "minLength": 1,
          "title": "minLength(1)",
          "type": "string"
        }
      },
      "required": [
        "idOrSlug"
      ],
      "type": "object"
    },
    "name": "get_event",
    "operationId": "events.get",
    "outputSchema": {
      "$defs": {
        "DateFromString": {
          "description": "a string to be decoded into a Date",
          "type": "string"
        }
      },
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "accentColor": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "bannerAssetId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "createdAt": {
          "$ref": "#/$defs/DateFromString"
        },
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "endsAt": {
          "anyOf": [
            {
              "$ref": "#/$defs/DateFromString"
            },
            {
              "type": "null"
            }
          ]
        },
        "id": {
          "type": "string"
        },
        "location": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "startsAt": {
          "anyOf": [
            {
              "$ref": "#/$defs/DateFromString"
            },
            {
              "type": "null"
            }
          ]
        },
        "timezone": {
          "type": "string"
        },
        "updatedAt": {
          "$ref": "#/$defs/DateFromString"
        },
        "version": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "slug",
        "name",
        "description",
        "location",
        "timezone",
        "startsAt",
        "endsAt",
        "bannerAssetId",
        "accentColor",
        "version",
        "createdAt",
        "updatedAt"
      ],
      "type": "object"
    }
  },
  {
    "description": "List events accessible to the current user or API key.",
    "inputSchema": {
      "$id": "/schemas/%7B%7D",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "anyOf": [
        {
          "type": "object"
        },
        {
          "type": "array"
        }
      ]
    },
    "name": "list_events",
    "operationId": "events.list",
    "outputSchema": {
      "$defs": {
        "DateFromString": {
          "description": "a string to be decoded into a Date",
          "type": "string"
        }
      },
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "items": {
        "additionalProperties": false,
        "properties": {
          "accentColor": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "bannerAssetId": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "createdAt": {
            "$ref": "#/$defs/DateFromString"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "endsAt": {
            "anyOf": [
              {
                "$ref": "#/$defs/DateFromString"
              },
              {
                "type": "null"
              }
            ]
          },
          "id": {
            "type": "string"
          },
          "location": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "name": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          },
          "startsAt": {
            "anyOf": [
              {
                "$ref": "#/$defs/DateFromString"
              },
              {
                "type": "null"
              }
            ]
          },
          "timezone": {
            "type": "string"
          },
          "updatedAt": {
            "$ref": "#/$defs/DateFromString"
          },
          "version": {
            "type": "number"
          }
        },
        "required": [
          "id",
          "slug",
          "name",
          "description",
          "location",
          "timezone",
          "startsAt",
          "endsAt",
          "bannerAssetId",
          "accentColor",
          "version",
          "createdAt",
          "updatedAt"
        ],
        "type": "object"
      },
      "type": "array"
    }
  }
];

export const partyIntents: readonly PartyIntentDescriptor[] = [
  {
    "inputSchema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "idOrSlug": {
          "description": "a string at least 1 character(s) long",
          "minLength": 1,
          "title": "minLength(1)",
          "type": "string"
        }
      },
      "required": [
        "idOrSlug"
      ],
      "type": "object"
    },
    "intentType": "events/get",
    "operationId": "events.get",
    "outputSchema": {
      "$defs": {
        "DateFromString": {
          "description": "a string to be decoded into a Date",
          "type": "string"
        }
      },
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "additionalProperties": false,
      "properties": {
        "accentColor": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "bannerAssetId": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "createdAt": {
          "$ref": "#/$defs/DateFromString"
        },
        "description": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "endsAt": {
          "anyOf": [
            {
              "$ref": "#/$defs/DateFromString"
            },
            {
              "type": "null"
            }
          ]
        },
        "id": {
          "type": "string"
        },
        "location": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "startsAt": {
          "anyOf": [
            {
              "$ref": "#/$defs/DateFromString"
            },
            {
              "type": "null"
            }
          ]
        },
        "timezone": {
          "type": "string"
        },
        "updatedAt": {
          "$ref": "#/$defs/DateFromString"
        },
        "version": {
          "type": "number"
        }
      },
      "required": [
        "id",
        "slug",
        "name",
        "description",
        "location",
        "timezone",
        "startsAt",
        "endsAt",
        "bannerAssetId",
        "accentColor",
        "version",
        "createdAt",
        "updatedAt"
      ],
      "type": "object"
    }
  }
];

export const openApi = {
  "info": {
    "title": "session-party API",
    "version": "0.1.0"
  },
  "openapi": "3.1.0",
  "paths": {
    "/events": {
      "get": {
        "operationId": "events.list",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$defs": {
                    "DateFromString": {
                      "description": "a string to be decoded into a Date",
                      "type": "string"
                    }
                  },
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "items": {
                    "additionalProperties": false,
                    "properties": {
                      "accentColor": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "bannerAssetId": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "createdAt": {
                        "$ref": "#/$defs/DateFromString"
                      },
                      "description": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "endsAt": {
                        "anyOf": [
                          {
                            "$ref": "#/$defs/DateFromString"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "id": {
                        "type": "string"
                      },
                      "location": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "name": {
                        "type": "string"
                      },
                      "slug": {
                        "type": "string"
                      },
                      "startsAt": {
                        "anyOf": [
                          {
                            "$ref": "#/$defs/DateFromString"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "timezone": {
                        "type": "string"
                      },
                      "updatedAt": {
                        "$ref": "#/$defs/DateFromString"
                      },
                      "version": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "id",
                      "slug",
                      "name",
                      "description",
                      "location",
                      "timezone",
                      "startsAt",
                      "endsAt",
                      "bannerAssetId",
                      "accentColor",
                      "version",
                      "createdAt",
                      "updatedAt"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                }
              }
            },
            "description": "Successful operation"
          }
        },
        "summary": "events.list",
        "x-authorization": {
          "kind": "authenticated"
        },
        "x-concurrency": "none",
        "x-emits": [],
        "x-idempotency": "none",
        "x-operation-kind": "query"
      },
      "post": {
        "operationId": "events.create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "additionalProperties": false,
                "properties": {
                  "accentColor": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "description": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "endsAt": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "location": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "description": "a string at most 200 character(s) long",
                    "maxLength": 200,
                    "minLength": 1,
                    "title": "maxLength(200)",
                    "type": "string"
                  },
                  "slug": {
                    "description": "a string matching the pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "maxLength": 80,
                    "minLength": 2,
                    "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "title": "maxLength(80)",
                    "type": "string"
                  },
                  "startsAt": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "timezone": {
                    "description": "a string at least 1 character(s) long",
                    "minLength": 1,
                    "title": "minLength(1)",
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "slug"
                ],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$defs": {
                    "DateFromString": {
                      "description": "a string to be decoded into a Date",
                      "type": "string"
                    }
                  },
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "additionalProperties": false,
                  "properties": {
                    "accentColor": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "bannerAssetId": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "createdAt": {
                      "$ref": "#/$defs/DateFromString"
                    },
                    "description": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "endsAt": {
                      "anyOf": [
                        {
                          "$ref": "#/$defs/DateFromString"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "id": {
                      "type": "string"
                    },
                    "location": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "name": {
                      "type": "string"
                    },
                    "slug": {
                      "type": "string"
                    },
                    "startsAt": {
                      "anyOf": [
                        {
                          "$ref": "#/$defs/DateFromString"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "timezone": {
                      "type": "string"
                    },
                    "updatedAt": {
                      "$ref": "#/$defs/DateFromString"
                    },
                    "version": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "id",
                    "slug",
                    "name",
                    "description",
                    "location",
                    "timezone",
                    "startsAt",
                    "endsAt",
                    "bannerAssetId",
                    "accentColor",
                    "version",
                    "createdAt",
                    "updatedAt"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "Successful operation"
          }
        },
        "summary": "events.create",
        "x-authorization": {
          "kind": "browser-session"
        },
        "x-concurrency": "none",
        "x-emits": [],
        "x-idempotency": "none",
        "x-operation-kind": "command"
      }
    },
    "/events/{idOrSlug}": {
      "get": {
        "operationId": "events.get",
        "parameters": [
          {
            "in": "path",
            "name": "idOrSlug",
            "required": true,
            "schema": {
              "description": "a string at least 1 character(s) long",
              "minLength": 1,
              "title": "minLength(1)",
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$defs": {
                    "DateFromString": {
                      "description": "a string to be decoded into a Date",
                      "type": "string"
                    }
                  },
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "additionalProperties": false,
                  "properties": {
                    "accentColor": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "bannerAssetId": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "createdAt": {
                      "$ref": "#/$defs/DateFromString"
                    },
                    "description": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "endsAt": {
                      "anyOf": [
                        {
                          "$ref": "#/$defs/DateFromString"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "id": {
                      "type": "string"
                    },
                    "location": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "name": {
                      "type": "string"
                    },
                    "slug": {
                      "type": "string"
                    },
                    "startsAt": {
                      "anyOf": [
                        {
                          "$ref": "#/$defs/DateFromString"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "timezone": {
                      "type": "string"
                    },
                    "updatedAt": {
                      "$ref": "#/$defs/DateFromString"
                    },
                    "version": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "id",
                    "slug",
                    "name",
                    "description",
                    "location",
                    "timezone",
                    "startsAt",
                    "endsAt",
                    "bannerAssetId",
                    "accentColor",
                    "version",
                    "createdAt",
                    "updatedAt"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "Successful operation"
          }
        },
        "summary": "events.get",
        "x-authorization": {
          "kind": "authenticated"
        },
        "x-concurrency": "none",
        "x-emits": [],
        "x-idempotency": "none",
        "x-operation-kind": "query"
      },
      "patch": {
        "operationId": "events.update",
        "parameters": [
          {
            "in": "path",
            "name": "idOrSlug",
            "required": true,
            "schema": {
              "description": "a string at least 1 character(s) long",
              "minLength": 1,
              "title": "minLength(1)",
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "additionalProperties": false,
                "properties": {
                  "accentColor": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "description": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "endsAt": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "location": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "name": {
                    "description": "a string at most 200 character(s) long",
                    "maxLength": 200,
                    "minLength": 1,
                    "title": "maxLength(200)",
                    "type": "string"
                  },
                  "slug": {
                    "description": "a string matching the pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "maxLength": 80,
                    "minLength": 2,
                    "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "title": "maxLength(80)",
                    "type": "string"
                  },
                  "startsAt": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ]
                  },
                  "timezone": {
                    "description": "a string at least 1 character(s) long",
                    "minLength": 1,
                    "title": "minLength(1)",
                    "type": "string"
                  }
                },
                "required": [],
                "type": "object"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$defs": {
                    "DateFromString": {
                      "description": "a string to be decoded into a Date",
                      "type": "string"
                    }
                  },
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "additionalProperties": false,
                  "properties": {
                    "accentColor": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "bannerAssetId": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "createdAt": {
                      "$ref": "#/$defs/DateFromString"
                    },
                    "description": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "endsAt": {
                      "anyOf": [
                        {
                          "$ref": "#/$defs/DateFromString"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "id": {
                      "type": "string"
                    },
                    "location": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "name": {
                      "type": "string"
                    },
                    "slug": {
                      "type": "string"
                    },
                    "startsAt": {
                      "anyOf": [
                        {
                          "$ref": "#/$defs/DateFromString"
                        },
                        {
                          "type": "null"
                        }
                      ]
                    },
                    "timezone": {
                      "type": "string"
                    },
                    "updatedAt": {
                      "$ref": "#/$defs/DateFromString"
                    },
                    "version": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "id",
                    "slug",
                    "name",
                    "description",
                    "location",
                    "timezone",
                    "startsAt",
                    "endsAt",
                    "bannerAssetId",
                    "accentColor",
                    "version",
                    "createdAt",
                    "updatedAt"
                  ],
                  "type": "object"
                }
              }
            },
            "description": "Successful operation"
          }
        },
        "summary": "events.update",
        "x-authorization": {
          "kind": "authenticated"
        },
        "x-concurrency": "none",
        "x-emits": [],
        "x-idempotency": "none",
        "x-operation-kind": "command"
      }
    }
  }
} as const satisfies OpenApiDocument;

export const ownershipManifest = {
  "mcp": [
    {
      "name": "get_event",
      "operationId": "events.get"
    },
    {
      "name": "list_events",
      "operationId": "events.list"
    }
  ],
  "operations": [
    {
      "operationId": "events.create",
      "owner": "events",
      "source": "src/features/events/operations.ts"
    },
    {
      "operationId": "events.get",
      "owner": "events",
      "source": "src/features/events/operations.ts"
    },
    {
      "operationId": "events.list",
      "owner": "events",
      "source": "src/features/events/operations.ts"
    },
    {
      "operationId": "events.update",
      "owner": "events",
      "source": "src/features/events/operations.ts"
    }
  ],
  "party": [
    {
      "intentType": "events/get",
      "operationId": "events.get"
    }
  ],
  "rest": [
    {
      "method": "post",
      "operationId": "events.create",
      "path": "/events"
    },
    {
      "method": "get",
      "operationId": "events.get",
      "path": "/events/:idOrSlug"
    },
    {
      "method": "get",
      "operationId": "events.list",
      "path": "/events"
    },
    {
      "method": "patch",
      "operationId": "events.update",
      "path": "/events/:idOrSlug"
    }
  ]
} as const satisfies RegistryOwnershipManifest;

// Compatibility exports include only slices that have not cut over to OperationDefs.
export const apiRouters: readonly Hono<{ Bindings: Env }>[] = [];
export const tools: readonly ToolDef[] = [];
export const partyHandlers: Readonly<Record<string, PartyHandler>> = {};
