import eventsApi from "../features/events/api";
import { tools as eventsTools } from "../features/events/tools";
import type { ToolDef } from "contracts/mcp";
import type { Hono } from "hono";
import type { PartyHandler } from "./party/types";

// Generated by scripts/gen.ts. Do not edit by hand.
export const apiRouters: readonly Hono<{ Bindings: Env }>[] = [eventsApi];

export const tools: readonly ToolDef[] = [...eventsTools];

export const partyHandlers: Readonly<Record<string, PartyHandler>> = {};
