import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const featuresRoot = path.join(root, "src/features");
const outputPath = path.join(root, "src/server/registry.gen.ts");

const exists = async (file: string): Promise<boolean> =>
  readFile(file).then(
    () => true,
    () => false,
  );

const identifier = (slice: string): string =>
  slice.replace(/[^a-zA-Z0-9_$]/g, "_").replace(/^[0-9]/, "_$&");

const slices = (await readdir(featuresRoot, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b));

const files = await Promise.all(
  slices.map(async (slice) => ({
    slice,
    id: identifier(slice),
    api: await exists(path.join(featuresRoot, slice, "api.ts")),
    tools: await exists(path.join(featuresRoot, slice, "tools.ts")),
    party: await exists(path.join(featuresRoot, slice, "party.ts")),
  })),
);

const imports: string[] = [];
for (const file of files) {
  if (file.api) imports.push(`import ${file.id}Api from "../features/${file.slice}/api";`);
  if (file.tools) imports.push(`import { tools as ${file.id}Tools } from "../features/${file.slice}/tools";`);
  if (file.party) {
    imports.push(`import { handlers as ${file.id}Handlers } from "../features/${file.slice}/party";`);
  }
}

const apiEntries = files.filter((file) => file.api).map((file) => `${file.id}Api`);
const toolEntries = files.filter((file) => file.tools).map((file) => `...${file.id}Tools`);
const partyEntries = files.filter((file) => file.party).map((file) => `...${file.id}Handlers`);

const generated = `${
  imports.length ? `${imports.join("\n")}\n` : ""
}import type { ToolDef } from "contracts/mcp";
import type { Hono } from "hono";
import type { PartyHandler } from "./party/types";

// Generated by scripts/gen.ts. Do not edit by hand.
export const apiRouters: readonly Hono<{ Bindings: Env }>[] = [${apiEntries.join(", ")}];

export const tools: readonly ToolDef[] = [${toolEntries.join(", ")}];

export const partyHandlers: Readonly<Record<string, PartyHandler>> = {${partyEntries.join(", ")}};
`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("src/server/registry.gen.ts is stale; run pnpm gen");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated);
}

