import type { ClientRouteDefinition } from "./route-discovery";

// Generated by scripts/gen.ts. Do not edit by hand.
export const generatedClientRoutes = [
  {
    path: "/e/:eventSlug/agenda",
    contentWidth: "canvas",
    load: () => import("../features/agenda/routes/agenda"),
  },
  {
    path: "/e/:eventSlug/comms",
    contentWidth: "canvas",
    load: () => import("../features/comms/routes/comms"),
  },
  {
    path: "/speaker-directory",
    contentWidth: "wide",
    load: () => import("../features/directory/routes/speakers"),
  },
  {
    path: "/e/:eventSlug",
    contentWidth: "compact",
    load: () => import("../features/events/routes/event-overview"),
  },
  {
    path: "/e/:eventSlug/settings",
    contentWidth: "compact",
    load: () => import("../features/events/routes/event-settings"),
  },
  {
    path: "/events",
    contentWidth: "standard",
    load: () => import("../features/events/routes/events-home"),
  },
  {
    path: "/",
    layout: "bare",
    load: () => import("../features/events/routes/landing"),
  },
  {
    path: "/reviewer-invitations/accept",
    contentWidth: "compact",
    load: () => import("../features/events/routes/reviewer-invitation"),
  },
  {
    path: "/e/:eventSlug/exports",
    contentWidth: "compact",
    load: () => import("../features/exports/routes/exports"),
  },
  {
    path: "/e/:eventSlug/forms",
    contentWidth: "canvas",
    load: () => import("../features/forms/routes/forms"),
  },
  {
    path: "/staff",
    contentWidth: "standard",
    load: () => import("../features/install/routes/staff"),
  },
  {
    path: "/e/:eventSlug/integrations",
    contentWidth: "wide",
    load: () => import("../features/integrations/routes/integrations"),
  },
  {
    path: "/e/:eventSlug/content",
    contentWidth: "wide",
    load: () => import("../features/portal/routes/organizer-content"),
  },
  {
    path: "/e/:eventSlug/dashboard",
    contentWidth: "canvas",
    load: () => import("../features/portal/routes/organizer-dashboard"),
  },
  {
    path: "/e/:eventSlug/resources",
    contentWidth: "standard",
    load: () => import("../features/portal/routes/organizer-resources"),
  },
  {
    path: "/e/:eventSlug/speakers/:speakerId",
    load: () => import("../features/portal/routes/organizer-speaker-detail"),
  },
  {
    path: "/e/:eventSlug/speakers",
    contentWidth: "wide",
    load: () => import("../features/portal/routes/organizer-speakers"),
  },
  {
    path: "/e/:eventSlug/tasks",
    contentWidth: "standard",
    load: () => import("../features/portal/routes/organizer-tasks"),
  },
  {
    path: "/embed/:eventSlug/speakers",
    layout: "bare",
    load: () => import("../features/portal/routes/public-speakers"),
  },
  {
    path: "/e/:eventSlug/portal/*",
    layout: "bare",
    load: () => import("../features/portal/routes/speaker-portal"),
  },
  {
    path: "/speakers/:speakerSlug",
    layout: "bare",
    load: () => import("../features/profiles/routes/public-profile"),
  },
  {
    path: "/speaker/profile",
    load: () => import("../features/profiles/routes/reusable-profile"),
  },
  {
    path: "/embed/:eventSlug/:embedId",
    layout: "bare",
    load: () => import("../features/publication/routes/persisted-embed"),
  },
  {
    path: "/event/:eventSlug/*",
    layout: "bare",
    load: () => import("../features/publication/routes/public-program"),
  },
  {
    path: "/e/:eventSlug/publication",
    contentWidth: "wide",
    load: () => import("../features/publication/routes/publication"),
  },
  {
    path: "/embed/:eventSlug/schedule",
    layout: "bare",
    load: () => import("../features/publication/routes/schedule-embed"),
  },
  {
    path: "/e/:eventSlug/review",
    contentWidth: "canvas",
    load: () => import("../features/review/routes/review-workbench"),
  },
  {
    path: "/portal/events/:eventSlug/submissions",
    layout: "bare",
    load: () => import("../features/submit/routes/my-submissions"),
  },
  {
    path: "/submit/:eventSlug/:formId",
    layout: "bare",
    load: () => import("../features/submit/routes/public-submit"),
  },
  {
    path: "/e/:eventSlug/submissions",
    contentWidth: "wide",
    load: () => import("../features/submit/routes/submissions"),
  },
] as const satisfies readonly ClientRouteDefinition[];
