import type { AnyOperationDef } from "contracts/operation";
import { browserSessionAuthorization, publicAuthorization } from "contracts/principal";
import { Schema } from "effect";
import {
  BrandAsset,
  EventBrand,
  GetEventBrandInput,
  InstallationBrand,
  InstallationBrandAdmin,
  UpdateEventBrandInput,
  UpdateInstallationBrandInput,
  UploadBrandAssetInput,
} from "./schema";
import {
  getEventBrand,
  getInstallationBrand,
  getInstallationBrandAdmin,
  updateEventBrand,
  updateInstallationBrand,
  uploadBrandAsset,
} from "./service";

export const operations = [
  {
    id: "branding.get",
    kind: "query",
    input: Schema.Struct({}),
    output: InstallationBrand,
    authorize: publicAuthorization,
    invoke: getInstallationBrand,
    rest: { method: "get", path: "/brand", input: {}, summary: "Get public installation branding", successStatus: 200 },
    idempotency: "none",
    concurrency: "none",
    emits: [],
  } satisfies AnyOperationDef,
  {
    id: "branding.getAdmin",
    kind: "query",
    input: Schema.Struct({}),
    output: InstallationBrandAdmin,
    authorize: browserSessionAuthorization,
    invoke: getInstallationBrandAdmin,
    rest: { method: "get", path: "/brand/manage", input: {}, summary: "Get installation branding for setup and administration", successStatus: 200 },
    idempotency: "none",
    concurrency: "none",
    emits: [],
  } satisfies AnyOperationDef,
  {
    id: "branding.update",
    kind: "command",
    input: UpdateInstallationBrandInput,
    output: InstallationBrandAdmin,
    authorize: browserSessionAuthorization,
    invoke: updateInstallationBrand,
    rest: { method: "patch", path: "/brand", input: { body: "all" }, summary: "Configure installation branding", successStatus: 200 },
    idempotency: "none",
    concurrency: "required",
    emits: ["branding.installation.updated"],
  } satisfies AnyOperationDef,
  {
    id: "branding.uploadAsset",
    kind: "command",
    input: UploadBrandAssetInput,
    output: BrandAsset,
    authorize: browserSessionAuthorization,
    invoke: uploadBrandAsset,
    rest: { method: "post", path: "/brand/assets", input: { body: "all" }, summary: "Upload a constrained installation or event brand image", successStatus: 201 },
    idempotency: "none",
    concurrency: "none",
    emits: [],
  } satisfies AnyOperationDef,
  {
    id: "branding.getEvent",
    kind: "query",
    input: GetEventBrandInput,
    output: EventBrand,
    authorize: publicAuthorization,
    invoke: ({ eventId }: typeof GetEventBrandInput.Type) => getEventBrand(eventId),
    rest: { method: "get", path: "/events/:eventId/brand", input: { path: ["eventId"] }, summary: "Resolve public event branding", successStatus: 200 },
    idempotency: "none",
    concurrency: "none",
    emits: [],
  } satisfies AnyOperationDef,
  {
    id: "branding.updateEvent",
    kind: "command",
    input: UpdateEventBrandInput,
    output: EventBrand,
    authorize: browserSessionAuthorization,
    invoke: updateEventBrand,
    rest: { method: "patch", path: "/events/:eventId/brand", input: { path: ["eventId"], body: ["expectedVersion", "publicName", "inheritInstallationBrand", "logoAssetId", "bannerAssetId", "primaryColor"] }, summary: "Configure event branding overrides", successStatus: 200 },
    idempotency: "none",
    concurrency: "required",
    emits: ["branding.event.updated"],
  } satisfies AnyOperationDef,
] as const;

